import type { AIModel } from "../../types/ai.js";

export const AUDIO_MODELS: Record<string, AIModel> = {
  // ── Аудио ─────────────────────────────────────────────────────────────────
  "tts-openai": {
    id: "tts-openai",
    name: "🔊 Синтез речи (OpenAI)",
    description:
      "Синтез речи от OpenAI. Быстрая генерация, естественная интонация. Дешевле ElevenLabs, но меньше голосов и нет клонированных.",
    section: "audio",
    provider: "openai",
    costUsdPerRequest: 0,
    costUsdPerKChar: 0.015, // tts-1: $0.015/1K chars (default)
    inputCostUsdPerMToken: 0,
    outputCostUsdPerMToken: 0,
    costVariants: {
      settingKey: "model",
      map: {
        "tts-1": { costUsdPerKChar: 0.015 },
        "tts-1-hd": { costUsdPerKChar: 0.03 },
        "gpt-4o-mini-tts": { costUsdPerKChar: 0.015 },
      },
    },
    supportsImages: false,
    supportsVoice: false,
    supportsWeb: false,
    isAsync: false,
    contextStrategy: "db_history",
    contextMaxMessages: 0,
    settings: [
      {
        key: "model",
        label: "Модель TTS",
        description:
          "tts-1 — стандартное качество, tts-1-hd — высокое качество, gpt-4o-mini-tts — управляемый стиль речи через инструкции. Влияет на цену.",
        type: "select",
        options: [
          { value: "tts-1", label: "TTS-1 (Standard)" },
          { value: "tts-1-hd", label: "TTS-1 HD" },
          { value: "gpt-4o-mini-tts", label: "GPT-4o Mini TTS" },
        ],
        default: "tts-1",
      },
      {
        key: "voice",
        label: "Голос",
        description: "Тембр и стиль диктора. Нажмите ▶ чтобы прослушать сэмпл.",
        type: "openai-voice-picker",
        default: "onyx",
      },
      {
        key: "speed",
        label: "Скорость речи",
        description: "Темп озвучки: 1.0 — нормальная скорость, ниже — медленнее, выше — быстрее.",
        type: "slider",
        min: 0.25,
        max: 4.0,
        step: 0.05,
        default: 1.0,
      },
      {
        key: "format",
        label: "Формат аудио",
        description: "MP3 — универсальный и компактный, FLAC — без потерь, Opus — для стриминга.",
        type: "select",
        options: [
          { value: "mp3", label: "MP3" },
          { value: "opus", label: "Opus" },
          { value: "aac", label: "AAC" },
          { value: "flac", label: "FLAC" },
          { value: "wav", label: "WAV" },
        ],
        default: "mp3",
        advanced: true,
      },
      {
        key: "instructions",
        label: "Инструкции к голосу",
        description:
          "Только для gpt-4o-mini-tts: укажите тон, эмоцию и стиль речи. Например: 'Говори медленно и торжественно' или 'Эмоциональный диктор новостей'.",
        type: "text",
        default: "",
        advanced: true,
      },
    ],
  },
  "voice-clone": {
    id: "voice-clone",
    name: "🎤 Клонирование голоса",
    description:
      "Создаёт ваш голосовой профиль по короткому аудиообразцу (~5 сек). Готовый голос доступен в синтезе речи и видео-аватарах.",
    section: "audio",
    provider: "cartesia",
    costUsdPerRequest: 0,
    inputCostUsdPerMToken: 0,
    outputCostUsdPerMToken: 0,
    supportsImages: false,
    supportsVoice: true,
    supportsWeb: false,
    isAsync: false,
    contextStrategy: "db_history",
    contextMaxMessages: 0,
    settings: [],
  },
  "tts-cartesia": {
    id: "tts-cartesia",
    name: "🔊 Синтез речи (Cartesia)",
    description:
      "Cartesia Sonic — быстрый и дешёвый TTS с поддержкой ваших клонированных голосов и многих языков, включая русский.",
    section: "audio",
    provider: "cartesia",
    costUsdPerRequest: 0,
    // Cartesia sonic-3: $0.065/1K chars (примерно). Округлено для калькуляции.
    costUsdPerKChar: 0.05,
    inputCostUsdPerMToken: 0,
    outputCostUsdPerMToken: 0,
    supportsImages: false,
    supportsVoice: false,
    supportsWeb: false,
    isAsync: false,
    contextStrategy: "db_history",
    contextMaxMessages: 0,
    settings: [
      {
        key: "model_id",
        label: "Модель TTS",
        description:
          "sonic-3 — последняя версия с поддержкой эмоций, громкости и плавной скорости. sonic-2 — предыдущее поколение, дешевле.",
        type: "select",
        options: [
          { value: "sonic-3", label: "Sonic-3 (последняя)" },
          { value: "sonic-2", label: "Sonic-2" },
        ],
        default: "sonic-3",
      },
      {
        key: "voice_id",
        label: "Голос",
        description:
          "Выберите голос из официального каталога Cartesia или своих клонированных. Нажмите ▶ чтобы прослушать сэмпл.",
        type: "cartesia-voice-picker",
        default: "bf0a246a-8642-498a-9950-80c35e9276b5",
      },
      {
        key: "language",
        label: "Язык озвучки",
        description:
          "Язык произношения. auto — определяется по тексту/голосу. Выбор языка переопределяет автодетект.",
        type: "select",
        options: [
          { value: "auto", label: "Автоматически" },
          { value: "ru", label: "Русский" },
          { value: "en", label: "English" },
          { value: "es", label: "Español" },
          { value: "fr", label: "Français" },
          { value: "de", label: "Deutsch" },
          { value: "it", label: "Italiano" },
          { value: "pt", label: "Português" },
          { value: "pl", label: "Polski" },
          { value: "uk", label: "Українська" },
          { value: "tr", label: "Türkçe" },
          { value: "ar", label: "العربية" },
          { value: "zh", label: "中文" },
          { value: "ja", label: "日本語" },
          { value: "ko", label: "한국어" },
          { value: "hi", label: "हिन्दी" },
        ],
        default: "auto",
        advanced: true,
      },
      {
        key: "speed",
        label: "Скорость речи",
        description: "0.6× — медленнее, 1.0× — нормальная, 1.5× — быстрее. Только для sonic-3.",
        type: "slider",
        min: 0.6,
        max: 1.5,
        step: 0.05,
        default: 1.0,
        advanced: true,
        unavailableIf: { key: "model_id", neq: "sonic-3" },
      },
      {
        key: "volume",
        label: "Громкость",
        description: "0.5× — тише, 1.0× — обычная, 2.0× — громче. Только для sonic-3.",
        type: "slider",
        min: 0.5,
        max: 2.0,
        step: 0.05,
        default: 1.0,
        advanced: true,
        unavailableIf: { key: "model_id", neq: "sonic-3" },
      },
      {
        key: "emotion",
        label: "Эмоция",
        description:
          "Подсказка эмоциональной окраски речи. Работает только в sonic-3 и зависит от голоса.",
        type: "select",
        options: [
          { value: "", label: "Нейтрально (без подсказки)" },
          { value: "neutral", label: "Нейтрально" },
          { value: "calm", label: "Спокойно" },
          { value: "happy", label: "Радостно" },
          { value: "excited", label: "Воодушевлённо" },
          { value: "content", label: "Удовлетворённо" },
          { value: "sad", label: "Грустно" },
          { value: "angry", label: "Гневно" },
          { value: "scared", label: "Испуганно" },
          { value: "confident", label: "Уверенно" },
          { value: "curious", label: "Любопытно" },
          { value: "sarcastic", label: "Саркастично" },
          { value: "mysterious", label: "Таинственно" },
        ],
        default: "",
        advanced: true,
        unavailableIf: { key: "model_id", neq: "sonic-3" },
      },
    ],
  },
  "tts-el": {
    id: "tts-el",
    name: "🔊 Синтез речи (ElevenLabs)",
    description:
      "Синтез речи от ElevenLabs — широкая библиотека голосов + ваши клонированные. Выше качество и выразительность, чем OpenAI TTS, но дороже.",
    section: "audio",
    provider: "elevenlabs",
    costUsdPerRequest: 0,
    costUsdPerKChar: 0.3, // eleven_multilingual_v2: $0.24/1K chars
    inputCostUsdPerMToken: 0,
    outputCostUsdPerMToken: 0,
    costVariants: {
      settingKey: "model_id",
      map: {
        eleven_multilingual_v2: { costUsdPerKChar: 0.3 },
        eleven_turbo_v2_5: { costUsdPerKChar: 0.15 },
      },
    },
    supportsImages: false,
    supportsVoice: false,
    supportsWeb: false,
    isAsync: false,
    contextStrategy: "db_history",
    contextMaxMessages: 0,
    settings: [
      {
        key: "model_id",
        label: "Модель синтеза",
        description:
          "multilingual_v2 — максимальное качество (дороже), turbo_v2_5 — быстрее и в 2× дешевле.",
        type: "select",
        options: [
          { value: "eleven_multilingual_v2", label: "Multilingual v2 (макс. качество)" },
          { value: "eleven_turbo_v2_5", label: "Turbo v2.5 (быстрее, дешевле)" },
        ],
        default: "eleven_multilingual_v2",
      },
      {
        key: "voice_id",
        label: "Голос",
        description: "Выберите голос из официальной библиотеки ElevenLabs или своих клонированных.",
        type: "elevenlabs-voice-picker",
        default: "21m00Tcm4TlvDq8ikWAM",
      },
      {
        key: "stability",
        label: "Стабильность",
        description:
          "Однородность голоса: высокое значение — ровно и монотонно, низкое — эмоциональнее.",
        type: "slider",
        min: 0,
        max: 1,
        step: 0.05,
        default: 0.5,
        advanced: true,
      },
      {
        key: "similarity_boost",
        label: "Схожесть с оригиналом",
        description: "Насколько точно воспроизводится тембр выбранного голоса.",
        type: "slider",
        min: 0,
        max: 1,
        step: 0.05,
        default: 0.75,
        advanced: true,
      },
      {
        key: "style",
        label: "Выразительность стиля",
        description: "0 — нейтрально, 1 — максимально выразительно.",
        type: "slider",
        min: 0,
        max: 1,
        step: 0.05,
        default: 0.0,
        advanced: true,
      },
      {
        key: "use_speaker_boost",
        label: "Speaker Boost",
        description: "Усиление качества и чёткости голоса.",
        type: "toggle",
        default: true,
        advanced: true,
      },
    ],
  },
  suno: {
    id: "suno",
    name: "🎵 Suno (музыка с вокалом)",
    description:
      "Генерирует полноценные музыкальные треки с вокалом и аранжировкой. Можно задать стиль, настроение и текст песни. До 4 минут. Дольше ElevenLabs, но с полноценным вокалом.",
    section: "audio",
    provider: "apipass",
    costUsdPerRequest: 0.06, // ~$0.030–$0.040/track (apipass.net proxy)
    inputCostUsdPerMToken: 0,
    outputCostUsdPerMToken: 0,
    supportsImages: false,
    supportsVoice: false,
    supportsWeb: false,
    isAsync: true,
    contextStrategy: "db_history",
    contextMaxMessages: 0,
    settings: [
      {
        key: "model_version",
        label: "Версия модели",
        description:
          "V4 — базовая, V4.5 — рекомендуется (до 8 мин, стабильное качество), V4.5+ — повышенная детализация, V5 — новое поколение, V5.5 — последняя (экспериментальная).",
        type: "select",
        options: [
          { value: "V4", label: "V4" },
          { value: "V4_5", label: "V4.5 (рекомендуется)" },
          { value: "V4_5PLUS", label: "V4.5 Plus" },
          { value: "V5", label: "V5" },
          { value: "V5_5", label: "V5.5 (последняя)" },
        ],
        default: "V4_5",
      },
      {
        key: "make_instrumental",
        label: "Только инструментал",
        description: "Сгенерировать музыку без вокала — только инструментальную дорожку.",
        type: "toggle",
        default: false,
      },
      {
        key: "lyrics",
        label: "Текст песни",
        description: "Готовый текст для пения. Если указан — модель не генерирует текст сама.",
        type: "text",
        default: "",
      },
    ],
  },
  "sounds-el": {
    id: "sounds-el",
    name: "🔔 Звуковые эффекты (ElevenLabs)",
    description:
      "Генерирует оригинальные звуковые эффекты по описанию. Подходит для видеопроизводства, игр и подкастов. Рекомендуем задавать промпт на английском языке.",
    section: "audio",
    provider: "elevenlabs",
    costUsdPerRequest: 0.06,
    costUsdPerSecond: 0,
    inputCostUsdPerMToken: 0,
    outputCostUsdPerMToken: 0,
    supportsImages: false,
    supportsVoice: false,
    supportsWeb: false,
    isAsync: false,
    contextStrategy: "db_history",
    contextMaxMessages: 0,
    settings: [
      {
        key: "duration_seconds",
        label: "Длительность (сек)",
        description: "Конкретная длительность в секундах (1–30).",
        type: "slider",
        min: 1,
        max: 30,
        step: 1,
        default: null,
      },
      {
        key: "prompt_influence",
        label: "Влияние промпта",
        description:
          "Насколько точно звук следует описанию (0.0–1.0). Ниже — больше вариативности.",
        type: "slider",
        min: 0,
        max: 1,
        step: 0.05,
        default: 0.3,
        advanced: true,
      },
      {
        key: "auto_translate_prompt",
        label: "Автоперевод промпта",
        description:
          "Эта модель работает только (либо значительно лучше) с промптами на английском языке, мы можем перевести его для вас за отдельную плату.",
        type: "toggle",
        default: false,
      },
    ],
  },
  "music-el": {
    id: "music-el",
    name: "🎶 ElevenLabs (музыка без вокала)",
    description:
      "Генерирует фоновую музыку, амбиент и атмосферы через ElevenLabs. Инструментал без вокала, до 22 секунд. Быстрее Suno, но без пения. Промпт лучше на английском.",
    section: "audio",
    provider: "elevenlabs",
    costUsdPerRequest: 0,
    costUsdPerSecond: 0.008, // manual duration: 20 credits/sec × $0.00048/credit
    inputCostUsdPerMToken: 0,
    outputCostUsdPerMToken: 0,
    supportsImages: false,
    supportsVoice: false,
    supportsWeb: false,
    isAsync: false,
    contextStrategy: "db_history",
    contextMaxMessages: 0,
    settings: [
      {
        key: "auto_translate_prompt",
        label: "Автоперевод промпта",
        description:
          "Эта модель работает только (либо значительно лучше) с промптами на английском языке, мы можем перевести его для вас за отдельную плату.",
        type: "toggle",
        default: false,
      },
      {
        key: "duration_seconds",
        label: "Длительность (сек)",
        description: "Конкретная длительность в секундах (1–22).",
        type: "slider",
        min: 1,
        max: 22,
        step: 1,
        default: null,
      },
      {
        key: "prompt_influence",
        label: "Влияние промпта",
        description:
          "Насколько точно музыка следует описанию (0.0–1.0). Ниже — больше вариативности.",
        type: "slider",
        min: 0,
        max: 1,
        step: 0.05,
        default: 0.3,
        advanced: true,
      },
    ],
  },
};
