import type { AIModel, MediaInputSlot, ModelSettingDef } from "../../types/ai.js";
import { mkAspectRatio, mkNumImagesSetting, NUM_IMAGES_SETTING } from "./_helpers.js";

const MI_EDIT: MediaInputSlot = {
  slotKey: "edit",
  mode: "edit",
  labelKey: "edit",
};
const MI_EDIT_4: MediaInputSlot = {
  slotKey: "edit",
  mode: "edit",
  labelKey: "multiple_edit",
  maxImages: 4,
};
const MI_EDIT_8: MediaInputSlot = {
  slotKey: "edit",
  mode: "edit",
  labelKey: "multiple_edit",
  maxImages: 8,
};
const MI_EDIT_10: MediaInputSlot = {
  slotKey: "edit",
  mode: "edit",
  labelKey: "multiple_edit",
  maxImages: 10,
};
const MI_STYLE_REF: MediaInputSlot = {
  slotKey: "style_ref",
  mode: "style_reference",
  labelKey: "styleReference",
  maxImages: 5,
};

/** FLUX.2 [dev] generation controls. */
const FLUX_SETTINGS: ModelSettingDef[] = [
  {
    key: "num_inference_steps",
    label: "Шаги генерации",
    description:
      "Количество итераций обработки: больше шагов — детальнее и качественнее, но медленнее.",
    type: "slider",
    min: 1,
    max: 50,
    step: 1,
    default: 28,
    advanced: true,
  },
  {
    key: "guidance_scale",
    label: "Следование промпту (CFG)",
    description:
      "Насколько строго ИИ следует вашему тексту. Высокие значения — буквально, низкие — с творческой интерпретацией.",
    type: "slider",
    min: 0,
    max: 10,
    step: 0.5,
    default: 2.5,
    advanced: true,
  },
  {
    key: "acceleration",
    label: "Ускорение",
    description:
      "Скорость генерации: none — максимальное качество, regular — баланс, high — быстро.",
    type: "select",
    options: [
      { value: "none", label: "None" },
      { value: "regular", label: "Regular" },
      { value: "high", label: "High" },
    ],
    default: "regular",
    advanced: true,
  },
  {
    key: "enable_prompt_expansion",
    label: "Расширение промпта",
    description: "Автоматически дополняет промпт для улучшения результата.",
    type: "toggle",
    default: false,
  },
  {
    key: "output_format",
    label: "Формат файла",
    description: "Формат результирующего изображения.",
    type: "select",
    options: [
      { value: "png", label: "PNG" },
      { value: "jpeg", label: "JPEG" },
      { value: "webp", label: "WebP" },
    ],
    default: "png",
    advanced: true,
  },
  {
    key: "seed",
    label: "Seed",
    description: "Фиксированный seed для воспроизводимости результата. Пусто — случайный.",
    type: "number",
    min: 0,
    default: null,
    advanced: true,
  },
];

/** FLUX.2 [pro] generation controls. */
const FLUX_PRO_SETTINGS: ModelSettingDef[] = [
  {
    key: "output_format",
    label: "Формат файла",
    description: "Формат результирующего изображения.",
    type: "select",
    options: [
      { value: "jpeg", label: "JPEG" },
      { value: "png", label: "PNG" },
    ],
    default: "jpeg",
    advanced: true,
  },
  {
    key: "seed",
    label: "Seed",
    description: "Фиксированный seed для воспроизводимости результата. Пусто — случайный.",
    type: "number",
    min: 0,
    default: null,
    advanced: true,
  },
];

/** Ideogram v3 — shared generation controls (quality / balanced / turbo). */
const IDEOGRAM_SETTINGS: ModelSettingDef[] = [
  NUM_IMAGES_SETTING,
  mkAspectRatio([
    "1:1",
    "4:3",
    "3:4",
    "16:9",
    "9:16",
    "2:3",
    "3:2",
    "4:5",
    "5:4",
    "2:1",
    "1:2",
    "16:10",
    "10:16",
    "3:1",
    "1:3",
  ]),
  {
    key: "resolution",
    label: "Точное разрешение",
    description:
      "Задаёт точный размер в пикселях. Переопределяет aspect ratio. Оставьте None для автоматического выбора.",
    type: "select",
    options: [
      { value: "None", label: "None (авто)" },
      { value: "1024x1024", label: "1024×1024 (1:1)" },
      { value: "1280x768", label: "1280×768 (5:3)" },
      { value: "768x1280", label: "768×1280 (3:5)" },
      { value: "1344x768", label: "1344×768 (16:9)" },
      { value: "768x1344", label: "768×1344 (9:16)" },
      { value: "1216x832", label: "1216×832 (3:2)" },
      { value: "832x1216", label: "832×1216 (2:3)" },
      { value: "1152x896", label: "1152×896 (4:3)" },
      { value: "896x1152", label: "896×1152 (3:4)" },
      { value: "1088x896", label: "1088×896 (5:4)" },
      { value: "896x1088", label: "896×1088 (4:5)" },
      { value: "1536x640", label: "1536×640 (2.4:1)" },
      { value: "640x1536", label: "640×1536 (1:2.4)" },
    ],
    default: "None",
  },
  {
    key: "style_type",
    label: "Стиль",
    description: "Художественное направление изображения.",
    type: "select",
    options: [
      { value: "None", label: "None" },
      { value: "Auto", label: "Auto" },
      { value: "General", label: "General" },
      {
        value: "Realistic",
        label: "Realistic",
        unavailableIf: { key: "style_preset", neq: "None" },
      },
      { value: "Design", label: "Design", unavailableIf: { key: "style_preset", neq: "None" } },
    ],
    default: "None",
  },
  {
    key: "style_preset",
    label: "Художественный пресет",
    description: "Готовый художественный стиль для изображения (только модели V3).",
    type: "dropdown",
    advanced: true,
    unavailableIf: {
      or: [
        { key: "style_type", eq: "Realistic" },
        { key: "style_type", eq: "Design" },
      ],
    },
    options: [
      { value: "None", label: "None" },
      { value: "80s Illustration", label: "80s Illustration" },
      { value: "90s Nostalgia", label: "90s Nostalgia" },
      { value: "Abstract Organic", label: "Abstract Organic" },
      { value: "Analog Nostalgia", label: "Analog Nostalgia" },
      { value: "Art Brut", label: "Art Brut" },
      { value: "Art Deco", label: "Art Deco" },
      { value: "Art Poster", label: "Art Poster" },
      { value: "Aura", label: "Aura" },
      { value: "Avant Garde", label: "Avant Garde" },
      { value: "Bauhaus", label: "Bauhaus" },
      { value: "Blueprint", label: "Blueprint" },
      { value: "Blurry Motion", label: "Blurry Motion" },
      { value: "Bright Art", label: "Bright Art" },
      { value: "C4D Cartoon", label: "C4D Cartoon" },
      { value: "Children's Book", label: "Children's Book" },
      { value: "Collage", label: "Collage" },
      { value: "Coloring Book I", label: "Coloring Book I" },
      { value: "Coloring Book II", label: "Coloring Book II" },
      { value: "Cubism", label: "Cubism" },
      { value: "Dark Aura", label: "Dark Aura" },
      { value: "Doodle", label: "Doodle" },
      { value: "Double Exposure", label: "Double Exposure" },
      { value: "Dramatic Cinema", label: "Dramatic Cinema" },
      { value: "Editorial", label: "Editorial" },
      { value: "Emotional Minimal", label: "Emotional Minimal" },
      { value: "Ethereal Party", label: "Ethereal Party" },
      { value: "Expired Film", label: "Expired Film" },
      { value: "Flat Art", label: "Flat Art" },
      { value: "Flat Vector", label: "Flat Vector" },
      { value: "Forest Reverie", label: "Forest Reverie" },
      { value: "Geo Minimalist", label: "Geo Minimalist" },
      { value: "Glass Prism", label: "Glass Prism" },
      { value: "Golden Hour", label: "Golden Hour" },
      { value: "Graffiti I", label: "Graffiti I" },
      { value: "Graffiti II", label: "Graffiti II" },
      { value: "Halftone Print", label: "Halftone Print" },
      { value: "High Contrast", label: "High Contrast" },
      { value: "Hippie Era", label: "Hippie Era" },
      { value: "Iconic", label: "Iconic" },
      { value: "Japandi Fusion", label: "Japandi Fusion" },
      { value: "Jazzy", label: "Jazzy" },
      { value: "Long Exposure", label: "Long Exposure" },
      { value: "Magazine Editorial", label: "Magazine Editorial" },
      { value: "Minimal Illustration", label: "Minimal Illustration" },
      { value: "Mixed Media", label: "Mixed Media" },
      { value: "Monochrome", label: "Monochrome" },
      { value: "Nightlife", label: "Nightlife" },
      { value: "Oil Painting", label: "Oil Painting" },
      { value: "Old Cartoons", label: "Old Cartoons" },
      { value: "Paint Gesture", label: "Paint Gesture" },
      { value: "Pop Art", label: "Pop Art" },
      { value: "Retro Etching", label: "Retro Etching" },
      { value: "Riviera Pop", label: "Riviera Pop" },
      { value: "Spotlight 80s", label: "Spotlight 80s" },
      { value: "Stylized Red", label: "Stylized Red" },
      { value: "Surreal Collage", label: "Surreal Collage" },
      { value: "Travel Poster", label: "Travel Poster" },
      { value: "Vintage Geo", label: "Vintage Geo" },
      { value: "Vintage Poster", label: "Vintage Poster" },
      { value: "Watercolor", label: "Watercolor" },
      { value: "Weird", label: "Weird" },
      { value: "Woodblock Print", label: "Woodblock Print" },
    ],
    default: "None",
  },
  {
    key: "magic_prompt_option",
    label: "Magic Prompt",
    description: "Автоматически улучшает ваш запрос для более красивого и детального результата.",
    type: "select",
    options: [
      { value: "Auto", label: "Auto" },
      { value: "On", label: "On" },
      { value: "Off", label: "Off" },
    ],
    default: "Auto",
  },
  {
    key: "negative_prompt",
    label: "Негативный промпт",
    description: "Что НЕ должно быть на картинке: перечислите нежелательные объекты или стили.",
    type: "text",
    default: "",
    advanced: true,
  },
  {
    key: "seed",
    label: "Seed",
    description: "Зерно генерации. Одинаковый seed при тех же параметрах даёт похожий результат.",
    type: "number",
    min: 0,
    max: 2147483647,
    default: null,
    advanced: true,
  },
];

/** Seedream guidance + seed. */
const SEEDREAM_SETTINGS: ModelSettingDef[] = [
  {
    key: "guidance_scale",
    label: "Следование промпту (CFG)",
    description:
      "Насколько строго ИИ следует вашему тексту: высокие значения — буквально, низкие — с творческой интерпретацией.",
    type: "slider",
    min: 1,
    max: 10,
    step: 0.5,
    default: 2.5,
    advanced: true,
  },
  {
    key: "seed",
    label: "Seed",
    description: "Число для воспроизведения результата. Пусто — случайный результат каждый раз.",
    type: "number",
    min: 0,
    max: 2147483647,
    default: null,
    advanced: true,
  },
];

/** Kling / Kling Pro video settings. */

export const DESIGN_MODELS: Record<string, AIModel> = {
  // Специализированная face-swap нейросеть (Replicate cdingram/face-swap).
  // Доступна ТОЛЬКО через готовый сценарий «Замена лица» в боте — поэтому
  // hiddenFromCarousel: модель не светится в карусели выбора моделей Дизайна.
  // mediaInputs.edit: [0] = референс-фото (сцена), [1] = фото лица.
  "face-swap-classic": {
    id: "face-swap-classic",
    name: "🔄 Замена лица",
    description: "Специализированная нейросеть для замены лица на фото.",
    section: "design",
    provider: "replicate",
    costUsdPerRequest: 0.09,
    inputCostUsdPerMToken: 0,
    outputCostUsdPerMToken: 0,
    supportsImages: true,
    supportsVoice: false,
    supportsWeb: false,
    isAsync: true,
    hiddenFromCarousel: true,
    contextStrategy: "db_history",
    contextMaxMessages: 0,
    supportedAspectRatios: ["auto"],
    mediaInputs: [{ slotKey: "edit", mode: "edit", labelKey: "multiple_edit", maxImages: 2 }],
  },
  // Готовый сценарий «Апскейл фото». Под капотом — nano-banana-pro (KIE primary,
  // evolink fallback): сцена `upscale.ts` зашивает resolution 4K, aspect_ratio
  // auto и фикс-промт. hiddenFromCarousel убирает модель из карусели Дизайна —
  // юзеру (и в карусели, и в подписях, и в биллинге) она видна только как
  // «📷 Апскейл фото», nano-banana нигде не светится.
  "image-upscale": {
    id: "image-upscale",
    name: "📷 Апскейл фото",
    description: "Увеличивает разрешение и чёткость фотографии до 4K.",
    section: "design",
    provider: "kie",
    costUsdPerRequest: 0.12, // nano-banana-pro @ 4K
    inputCostUsdPerMToken: 0,
    outputCostUsdPerMToken: 0,
    supportsImages: true,
    supportsVoice: false,
    supportsWeb: false,
    isAsync: true,
    hiddenFromCarousel: true,
    deliverAsDocument: true,
    contextStrategy: "db_history",
    contextMaxMessages: 0,
    supportedAspectRatios: ["auto"],
    mediaInputs: [{ slotKey: "edit", mode: "edit", labelKey: "multiple_edit", maxImages: 1 }],
  },
  "nano-banana-pro": {
    id: "nano-banana-pro",
    name: "🍌 Nano Banana PRO",
    description:
      "Генерирует реалистичные фото и позволяет менять детали словами. PRO — максимальное качество до 4K, дороже стандартной версии.",
    section: "design",
    provider: "kie",
    familyId: "nano-banana",
    versionLabel: "PRO",
    variantLabel: "Pro",
    costVariants: { settingKey: "resolution", map: { "1K": 0.09, "2K": 0.09, "4K": 0.12 } },
    costUsdPerRequest: 0.09,
    maxVirtualBatch: 4,
    inputCostUsdPerMToken: 0,
    outputCostUsdPerMToken: 0,
    supportsImages: true,
    mediaInputs: [MI_EDIT_8],
    supportsVoice: false,
    supportsWeb: false,
    isAsync: true,
    contextStrategy: "db_history",
    contextMaxMessages: 0,
    supportedAspectRatios: [
      "auto",
      "21:9",
      "16:9",
      "3:2",
      "4:3",
      "5:4",
      "1:1",
      "4:5",
      "3:4",
      "2:3",
      "9:16",
    ],
    settings: [
      NUM_IMAGES_SETTING,
      mkAspectRatio([
        "auto",
        "21:9",
        "16:9",
        "3:2",
        "4:3",
        "5:4",
        "1:1",
        "4:5",
        "3:4",
        "2:3",
        "9:16",
      ]),
      {
        key: "resolution",
        label: "Разрешение",
        description:
          "Детализация итогового изображения: 1K — стандарт, 4K — максимальные детали. Влияет на цену.",
        type: "select",
        options: [
          { value: "1K", label: "1K" },
          { value: "2K", label: "2K" },
          { value: "4K", label: "4K" },
        ],
        default: "1K",
      },
      {
        key: "output_format",
        label: "Формат файла",
        description: "PNG — без потери качества, JPEG — компактнее.",
        type: "select",
        options: [
          { value: "png", label: "PNG" },
          { value: "jpeg", label: "JPEG" },
        ],
        default: "png",
        advanced: true,
      },
    ],
  },
  "nano-banana-2": {
    id: "nano-banana-2",
    name: "🍌 Nano Banana 2",
    description:
      "Генерирует реалистичные фото и редактирует их по текстовым командам. Standard — дешевле PRO, поддерживает большее число референсов и расширенный набор соотношений сторон.",
    section: "design",
    provider: "kie",
    familyId: "nano-banana",
    versionLabel: "2",
    variantLabel: "Standard",
    costVariants: {
      settingKey: "resolution",
      map: { "1K": 0.04, "2K": 0.06, "4K": 0.09 },
    },
    costUsdPerRequest: 0.04,
    maxVirtualBatch: 4,
    inputCostUsdPerMToken: 0,
    outputCostUsdPerMToken: 0,
    supportsImages: true,
    mediaInputs: [
      {
        slotKey: "edit",
        mode: "edit",
        labelKey: "multiple_edit",
        maxImages: 14,
      },
    ],
    supportsVoice: false,
    supportsWeb: false,
    isAsync: true,
    contextStrategy: "db_history",
    contextMaxMessages: 0,
    supportedAspectRatios: [
      "auto",
      "21:9",
      "16:9",
      "4:3",
      "3:2",
      "5:4",
      "1:1",
      "4:5",
      "2:3",
      "3:4",
      "9:16",
      "8:1",
      "4:1",
      "1:4",
      "1:8",
    ],
    settings: [
      NUM_IMAGES_SETTING,
      mkAspectRatio([
        "auto",
        "21:9",
        "16:9",
        "4:3",
        "3:2",
        "5:4",
        "1:1",
        "4:5",
        "2:3",
        "3:4",
        "9:16",
        "8:1",
        "4:1",
        "1:4",
        "1:8",
      ]),
      {
        key: "resolution",
        label: "Разрешение",
        description:
          "Детализация итогового изображения: 1K — стандарт, 4K — максимальные детали. Влияет на цену.",
        type: "select",
        options: [
          { value: "1K", label: "1K" },
          { value: "2K", label: "2K" },
          { value: "4K", label: "4K" },
        ],
        default: "1K",
      },
      {
        key: "output_format",
        label: "Формат файла",
        description: "PNG — без потери качества, JPEG — компактнее.",
        type: "select",
        options: [
          { value: "png", label: "PNG" },
          { value: "jpeg", label: "JPEG" },
        ],
        default: "jpeg",
        advanced: true,
      },
    ],
  },
  "nano-banana-1": {
    id: "nano-banana-1",
    name: "🍌 Nano Banana",
    description:
      "Базовая версия: генерирует и редактирует фото по тексту. Дешевле PRO и v2, но без выбора разрешения и расширенных настроек.",
    section: "design",
    provider: "kie",
    familyId: "nano-banana",
    versionLabel: "1",
    variantLabel: "Standard",
    costUsdPerRequest: 0.02,
    maxVirtualBatch: 4,
    inputCostUsdPerMToken: 0,
    outputCostUsdPerMToken: 0,
    supportsImages: true,
    mediaInputs: [
      {
        slotKey: "edit",
        mode: "edit",
        labelKey: "multiple_edit",
        maxImages: 10,
      },
    ],
    supportsVoice: false,
    supportsWeb: false,
    isAsync: true,
    contextStrategy: "db_history",
    contextMaxMessages: 0,
    supportedAspectRatios: [
      "auto",
      "21:9",
      "16:9",
      "3:2",
      "4:3",
      "5:4",
      "1:1",
      "4:5",
      "3:4",
      "2:3",
      "9:16",
    ],
    settings: [
      NUM_IMAGES_SETTING,
      mkAspectRatio([
        "auto",
        "21:9",
        "16:9",
        "3:2",
        "4:3",
        "5:4",
        "1:1",
        "4:5",
        "3:4",
        "2:3",
        "9:16",
      ]),
      {
        key: "output_format",
        label: "Формат файла",
        description: "PNG — без потери качества, JPEG — компактнее.",
        type: "select",
        options: [
          { value: "png", label: "PNG" },
          { value: "jpeg", label: "JPEG" },
        ],
        default: "png",
        advanced: true,
      },
    ],
  },
  "higgsfield-soul": {
    id: "higgsfield-soul",
    name: "🧬 Higgsfield Soul 2.0",
    description:
      "Генерация изображений с вашим персонажем (Soul ID). Создайте персонажа из 20+ фотографий — и генерируйте любые сцены с его внешностью. Поддерживает стили, референсные изображения и режим batch.",
    section: "design",
    provider: "higgsfield",
    promptOptional: true,
    promptOptionalRequiresMedia: true,
    costUsdPerRequest: 0.09,
    costMatrix: {
      dims: ["resolution", "batch_size"],
      table: {
        "720p__1": 0.09,
        "720p__4": 0.13,
        "1080p__1": 0.19,
        "1080p__4": 0.31,
      },
    },
    inputCostUsdPerMToken: 0,
    outputCostUsdPerMToken: 0,
    supportsImages: true,
    mediaInputs: [{ slotKey: "edit", mode: "edit", labelKey: "reference" }],
    supportsVoice: false,
    supportsWeb: false,
    isAsync: true,
    contextStrategy: "db_history",
    contextMaxMessages: 0,
    supportedAspectRatios: ["4:3", "9:16", "16:9", "3:4", "1:1", "2:3", "3:2"],
    settings: [
      {
        key: "custom_reference_id",
        label: "Персонаж (Soul ID)",
        description: "Выберите созданного персонажа. Обязательно для генерации.",
        type: "soul-picker",
        default: null,
      },
      {
        key: "custom_reference_strength",
        label: "Сила персонажа",
        description:
          "Насколько сильно внешность персонажа влияет на результат (0 — слабо, 1 — максимально).",
        type: "slider",
        min: 0,
        max: 1,
        step: 0.05,
        default: 1,
      },
      mkAspectRatio(["4:3", "9:16", "16:9", "3:4", "1:1", "2:3", "3:2"]),
      {
        key: "resolution",
        label: "Разрешение",
        description: "Качество выходного изображения. 1080p дороже, но детальнее.",
        type: "select",
        options: [
          { value: "720p", label: "720p" },
          { value: "1080p", label: "1080p" },
        ],
        default: "720p",
      },
      {
        key: "batch_size",
        label: "Кол-во изображений",
        description: "Сколько вариантов сгенерировать за один запрос (1 или 4).",
        type: "select",
        options: [
          { value: 1, label: "1" },
          { value: 4, label: "4" },
        ],
        default: 1,
      },
      {
        key: "enhance_prompt",
        label: "Улучшение промпта",
        description: "Автоматически улучшает ваш промпт для более детального результата.",
        type: "toggle",
        default: true,
      },
      {
        key: "style_id",
        label: "Стиль (Soul Style)",
        description: "Выберите стиль для генерации — определяет настроение, цвета и эстетику.",
        type: "soul-style-picker",
        default: null,
      },
      {
        key: "style_strength",
        label: "Сила стиля",
        description: "Насколько сильно стиль влияет на результат (0 — слабо, 1 — максимально).",
        type: "slider",
        min: 0,
        max: 1,
        step: 0.05,
        default: 1,
        advanced: true,
      },
      {
        key: "seed",
        label: "Seed",
        description:
          "Фиксирует случайность генерации для воспроизводимых результатов (1–1 000 000). Оставьте пустым для случайного.",
        type: "number",
        min: 1,
        max: 1000000,
        default: null,
        advanced: true,
      },
    ],
  },
  "grok-imagine-image": {
    id: "grok-imagine-image",
    name: "🔮 Grok Imagine",
    description:
      "Генерация изображений от xAI (Grok). Text-to-image и image-to-image. Режим Quality — повышенная точность и детализация, Speed — быстрая генерация с большим количеством вариантов.",
    section: "design",
    provider: "kie",
    // Speed: $0.02 per 6 images, Quality: $0.025 per 4 images
    costUsdPerRequest: 0.02,
    costVariants: {
      settingKey: "enable_pro",
      map: { false: 0.02, true: 0.025 },
    },
    inputCostUsdPerMToken: 0,
    outputCostUsdPerMToken: 0,
    supportsImages: true,
    mediaInputs: [MI_EDIT],
    supportsVoice: false,
    supportsWeb: false,
    isAsync: true,
    contextStrategy: "db_history",
    contextMaxMessages: 0,
    supportedAspectRatios: ["1:1", "2:3", "3:2", "16:9", "9:16"],
    settings: [
      mkAspectRatio(["1:1", "2:3", "3:2", "16:9", "9:16"]),
      {
        key: "enable_pro",
        label: "Режим",
        description:
          "Speed — быстрая генерация (6 вариантов), Quality — повышенное качество и точность (4 варианта). Влияет на цену.",
        type: "select",
        options: [
          { value: false, label: "Speed" },
          { value: true, label: "Quality" },
        ],
        default: false,
      },
      // {
      //   key: "nsfw_checker",
      //   label: "Фильтр контента",
      //   description:
      //     "Включить фильтрацию контента провайдером. При отключении результаты возвращаются напрямую от модели без дополнительной проверки.",
      //   type: "toggle",
      //   default: false,
      // },
    ],
  },
  "gpt-image-2": {
    id: "gpt-image-2",
    name: "🖼️ GPT Image 2",
    description:
      "Новейшая версия GPT Image. Лучше предыдущей в рендеринге текста и точности следования промпту.",
    section: "design",
    familyId: "gpt-image",
    versionLabel: "2",
    variantLabel: "Standard",
    // Временно проксируем через KIE. Прямая интеграция с OpenAI Images API
    // сохранена в виде закомментированного блока ниже: для отката снять
    // комменты, вернуть provider:"openai" и расширить условие в factory.ts.
    provider: "kie",
    // Базовая цена = 1K. Точная стоимость определяется variant-ом resolution.
    costUsdPerRequest: 0.03,
    costVariants: {
      settingKey: "resolution",
      map: { "1K": 0.03, "2K": 0.05, "4K": 0.08 },
    },
    inputCostUsdPerMToken: 0,
    outputCostUsdPerMToken: 0,
    supportsImages: true,
    mediaInputs: [MI_EDIT_4],
    supportsVoice: false,
    supportsWeb: false,
    isAsync: true,
    contextStrategy: "db_history",
    contextMaxMessages: 0,
    supportedAspectRatios: null,
    settings: [
      {
        key: "aspect_ratio",
        label: "Соотношение сторон",
        description:
          "Auto — модель сама подберёт исходя из промпта. Для 4K-разрешения нужно выбрать конкретное соотношение (не Auto и не 1:1).",
        type: "select",
        options: [
          // Auto допускает только 1K. При 2K/4K в picker'е разрешения этот
          // вариант становится недоступным — юзер должен явно выбрать AR.
          {
            value: "auto",
            label: "Auto",
            unavailableIf: {
              or: [
                { key: "resolution", eq: "2K" },
                { key: "resolution", eq: "4K" },
              ],
            },
          },
          // 1:1 несовместим с 4K (KIE-схема). При 4K — disabled.
          {
            value: "1:1",
            label: "1:1",
            unavailableIf: { key: "resolution", eq: "4K" },
          },
          { value: "16:9", label: "16:9" },
          { value: "9:16", label: "9:16" },
          { value: "4:3", label: "4:3" },
          { value: "3:4", label: "3:4" },
        ],
        default: "auto",
      },
      {
        key: "resolution",
        label: "Разрешение",
        description:
          "1K — стандарт, 4K — максимальные детали. Влияет на цену. 4K доступно только если соотношение сторон не auto и не 1:1.",
        type: "select",
        options: [
          { value: "1K", label: "1K" },
          // 2K несовместим с aspect_ratio = "auto" (KIE-схема: auto → только 1K).
          {
            value: "2K",
            label: "2K",
            unavailableIf: { key: "aspect_ratio", eq: "auto" },
          },
          // 4K несовместим с auto и 1:1.
          {
            value: "4K",
            label: "4K",
            unavailableIf: {
              or: [
                { key: "aspect_ratio", eq: "auto" },
                { key: "aspect_ratio", eq: "1:1" },
              ],
            },
          },
        ],
        default: "1K",
      },
      {
        key: "nsfw_checker",
        label: "NSFW-фильтр",
        description: "Если выключен — отключается фильтрация контента провайдером.",
        type: "select",
        options: [
          { value: "false", label: "Off" },
          { value: "true", label: "On" },
        ],
        default: "false",
        advanced: true,
      },
    ],
  },
  "gpt-image-1.5": {
    id: "gpt-image-1.5",
    name: "🖼️ GPT Image 1.5",
    description:
      "Лучше всех понимает сложные текстовые запросы. Точно рисует то, что вы описали, включая текст на картинках.",
    section: "design",
    familyId: "gpt-image",
    versionLabel: "1.5",
    variantLabel: "Standard",
    provider: "openai",
    // Точная цена определяется адаптером на основе quality × size. Базовое значение: medium 1024×1024.
    costUsdPerRequest: 0.034,
    costMatrix: {
      dims: ["quality", "size"],
      table: {
        low__1024x1024: 0.009,
        low__1536x1024: 0.013,
        low__1024x1536: 0.013,
        medium__1024x1024: 0.034,
        medium__1536x1024: 0.05,
        medium__1024x1536: 0.05,
        high__1024x1024: 0.133,
        high__1536x1024: 0.2,
        high__1024x1536: 0.2,
        auto__1024x1024: 0.034,
        auto__1536x1024: 0.05,
        auto__1024x1536: 0.05,
      },
    },
    inputCostUsdPerMToken: 0,
    outputCostUsdPerMToken: 0,
    supportsImages: true,
    mediaInputs: [MI_EDIT_4],
    supportsVoice: false,
    supportsWeb: false,
    isAsync: false,
    maxVirtualBatch: 4,
    contextStrategy: "db_history",
    contextMaxMessages: 0,
    supportedAspectRatios: null,
    settings: [
      NUM_IMAGES_SETTING,
      {
        key: "size",
        label: "Размер",
        description: "1024×1024 (1:1), 1536×1024 (16:9), 1024×1536 (9:16). Влияет на цену.",
        type: "select",
        options: [
          { value: "1024x1024", label: "1024 × 1024" },
          { value: "1536x1024", label: "1536 × 1024 (16:9)" },
          { value: "1024x1536", label: "1024 × 1536 (9:16)" },
        ],
        default: "1024x1024",
      },
      {
        key: "quality",
        label: "Качество",
        description: "Low — быстро, Medium — баланс, High — максимум. Влияет на цену",
        type: "select",
        options: [
          { value: "low", label: "Low" },
          { value: "medium", label: "Medium" },
          { value: "high", label: "High" },
          { value: "auto", label: "Auto" },
        ],
        default: "medium",
      },
      {
        key: "output_format",
        label: "Формат",
        description: "Формат сохраняемого изображения. PNG поддерживает прозрачность.",
        type: "select",
        options: [
          { value: "png", label: "PNG" },
          { value: "jpeg", label: "JPEG" },
          { value: "webp", label: "WebP" },
        ],
        default: "png",
        advanced: true,
      },
      {
        key: "output_compression",
        label: "Сжатие",
        description:
          "Степень сжатия для JPEG и WebP (0 — без потерь, 100 — максимальное сжатие). Не влияет на PNG.",
        type: "slider",
        min: 0,
        max: 100,
        step: 1,
        default: 100,
        advanced: true,
      },
      {
        key: "background",
        label: "Фон",
        description: "transparent — прозрачный фон (только PNG/WebP), opaque — непрозрачный.",
        type: "select",
        options: [
          { value: "auto", label: "Auto" },
          { value: "opaque", label: "Opaque" },
          { value: "transparent", label: "Transparent" },
        ],
        default: "auto",
      },
      {
        key: "moderation",
        label: "Модерация",
        description: "low — ослабленная фильтрация контента, auto — стандартная.",
        type: "select",
        options: [
          { value: "auto", label: "Auto" },
          { value: "low", label: "Low" },
        ],
        default: "auto",
        advanced: true,
      },
    ],
  },
  midjourney: {
    id: "midjourney",
    name: "🎨 MidJourney v7",
    description:
      "Создаёт самые красивые и стильные изображения. Лучший выбор для арта, иллюстраций и эффектных визуалов.",
    section: "design",
    provider: "replicate",
    costUsdPerRequest: 0.0085,
    inputCostUsdPerMToken: 0,
    outputCostUsdPerMToken: 0,
    supportsImages: true,
    mediaInputs: [MI_EDIT],
    supportsVoice: false,
    supportsWeb: false,
    isAsync: true,
    // Native batch: Replicate API параметром `num_outputs` возвращает 1-4 картинки
    // за один call. nativeBatchMax > 1 → virtual batch для модели не применяется.
    // chargePerOutput → finalize умножит стоимость на K (Replicate биллит per-image).
    nativeBatchMax: 4,
    chargePerOutput: true,
    contextStrategy: "db_history",
    contextMaxMessages: 0,
    supportedAspectRatios: [
      "1:1",
      "16:9",
      "9:16",
      "4:3",
      "3:4",
      "3:2",
      "2:3",
      "4:5",
      "5:4",
      "21:9",
      "9:21",
    ],
    settings: [
      NUM_IMAGES_SETTING,
      mkAspectRatio([
        "1:1",
        "16:9",
        "9:16",
        "4:3",
        "3:4",
        "3:2",
        "2:3",
        "4:5",
        "5:4",
        "21:9",
        "9:21",
      ]),
      {
        key: "model",
        label: "Модель",
        description: "dev — выше качество (~28 шагов), schnell — быстрая (~4 шага).",
        type: "select",
        options: [
          { value: "dev", label: "Dev" },
          { value: "schnell", label: "Schnell" },
        ],
        default: "dev",
        advanced: true,
      },
      {
        key: "num_inference_steps",
        label: "Шаги генерации",
        description: "Количество шагов денойзинга. Больше шагов — детальнее, но дольше.",
        type: "slider",
        min: 10,
        max: 50,
        step: 1,
        default: 28,
        advanced: true,
        unavailableIf: { key: "model", eq: "schnell" },
      },
      {
        key: "guidance_scale",
        label: "Guidance Scale",
        description: "Насколько строго соблюдается промпт. Меньше — реалистичнее (рек. 2–3.5).",
        type: "slider",
        min: 0,
        max: 10,
        step: 0.5,
        default: 3,
        advanced: true,
      },
      {
        key: "prompt_strength",
        label: "Сила промпта (img2img)",
        description:
          "Степень изменения при img2img. 0.1 = минимальные изменения, 1.0 = полная замена.",
        type: "slider",
        min: 0.1,
        max: 1,
        step: 0.05,
        default: 0.8,
        advanced: true,
        unavailableIf: { key: "model", eq: "schnell" },
      },
      {
        key: "go_fast",
        label: "Быстрый режим",
        description: "fp8-квантизация вместо bf16. Быстрее, чуть ниже качество.",
        type: "toggle",
        default: false,
        advanced: true,
      },
      {
        key: "output_format",
        label: "Формат",
        description: "Формат результирующего изображения.",
        type: "select",
        options: [
          { value: "png", label: "PNG" },
          { value: "jpg", label: "JPG" },
          { value: "webp", label: "WebP" },
        ],
        default: "png",
        advanced: true,
      },
      {
        key: "output_quality",
        label: "Качество вывода",
        description: "Качество сжатия (0–100). Не влияет на PNG.",
        type: "slider",
        min: 0,
        max: 100,
        step: 1,
        default: 80,
        advanced: true,
      },
      {
        key: "extra_lora",
        label: "Дополнительная LoRA",
        description: "URL или путь к LoRA-весам (HuggingFace, CivitAI, Replicate, .safetensors).",
        type: "text",
        default: null,
        advanced: true,
      },
      {
        key: "lora_scale",
        label: "Сила LoRA",
        description: "Интенсивность основной LoRA. Оптимально: 0–1.",
        type: "slider",
        min: -1,
        max: 3,
        step: 0.1,
        default: 1,
        advanced: true,
      },
      {
        key: "extra_lora_scale",
        label: "Сила доп. LoRA",
        description: "Интенсивность дополнительной LoRA. Оптимально: 0–1.",
        type: "slider",
        min: -1,
        max: 3,
        step: 0.1,
        default: 1,
        advanced: true,
      },
      {
        key: "seed",
        label: "Seed",
        description: "Фиксированный seed для воспроизводимости результата.",
        type: "number",
        min: 0,
        default: null,
        advanced: true,
      },
      {
        key: "disable_safety_checker",
        label: "Отключить фильтр",
        description: "Отключить проверку безопасности контента.",
        type: "toggle",
        default: false,
        advanced: true,
      },
    ],
  },
  "seedream-5": {
    id: "seedream-5",
    name: "🛍️ Seedream 5.0 (ByteDance)",
    description:
      "Идеально для товарных фото, одежды и каталогов. Версия 5.0 — улучшенное качество и реалистичность по сравнению с 4.5.",
    section: "design",
    provider: "fal",
    familyId: "seedream",
    versionLabel: "5.0",
    variantLabel: "Standard",
    costUsdPerRequest: 0.035,
    inputCostUsdPerMToken: 0,
    outputCostUsdPerMToken: 0,
    supportsImages: true,
    mediaInputs: [MI_EDIT_10],
    supportsVoice: false,
    supportsWeb: false,
    isAsync: true,
    // Native batch: FAL seedream принимает num_images (1-6) за один call.
    // Биллинг per-image — chargePerOutput на модели включён, finalize × K.
    nativeBatchMax: 6,
    chargePerOutput: true,
    contextStrategy: "db_history",
    contextMaxMessages: 0,
    supportedAspectRatios: ["1:1", "4:3", "3:4", "16:9", "9:16"],
    settings: [
      mkNumImagesSetting(6),
      mkAspectRatio(["1:1", "4:3", "3:4", "16:9", "9:16"]),
      ...SEEDREAM_SETTINGS,
    ],
  },
  "seedream-4.5": {
    id: "seedream-4.5",
    name: "🛍️ Seedream 4.5",
    description:
      "Предыдущая версия Seedream — чуть проще, чем 5.0, но проверенная стабильность. Подойдёт для массовой генерации товарных фото.",
    section: "design",
    provider: "fal",
    familyId: "seedream",
    versionLabel: "4.5",
    variantLabel: "Standard",
    costUsdPerRequest: 0.04,
    inputCostUsdPerMToken: 0,
    outputCostUsdPerMToken: 0,
    supportsImages: true,
    mediaInputs: [MI_EDIT_10],
    supportsVoice: false,
    supportsWeb: false,
    isAsync: true,
    // Native batch: FAL seedream принимает num_images (1-6) за один call.
    // Биллинг per-image — chargePerOutput на модели включён, finalize × K.
    nativeBatchMax: 6,
    chargePerOutput: true,
    contextStrategy: "db_history",
    contextMaxMessages: 0,
    supportedAspectRatios: ["1:1", "4:3", "3:4", "16:9", "9:16"],
    settings: [
      mkNumImagesSetting(6),
      mkAspectRatio(["1:1", "4:3", "3:4", "16:9", "9:16"]),
      ...SEEDREAM_SETTINGS,
    ],
  },
  "ideogram-quality": {
    id: "ideogram-quality",
    name: "✍️ Ideogram v3.0 Quality",
    description:
      "Лучше всех рисует читаемый текст на картинках. Идеален для логотипов, постеров и рекламы. Quality — максимальная детализация и точность, самый медленный и дорогой вариант.",
    section: "design",
    provider: "replicate",
    familyId: "ideogram",
    variantLabel: "Quality",
    costUsdPerRequest: 0.09,
    inputCostUsdPerMToken: 0,
    outputCostUsdPerMToken: 0,
    supportsImages: true,
    mediaInputs: [MI_STYLE_REF],
    supportsVoice: false,
    supportsWeb: false,
    isAsync: true,
    maxVirtualBatch: 4,
    contextStrategy: "db_history",
    contextMaxMessages: 0,
    supportedAspectRatios: [
      "1:1",
      "4:3",
      "3:4",
      "16:9",
      "9:16",
      "2:3",
      "3:2",
      "4:5",
      "5:4",
      "2:1",
      "1:2",
      "16:10",
      "10:16",
      "3:1",
      "1:3",
    ],
    settings: IDEOGRAM_SETTINGS,
  },
  "ideogram-balanced": {
    id: "ideogram-balanced",
    name: "✍️ Ideogram v3.0 Balanced",
    description:
      "Лучше всех рисует читаемый текст на картинках. Идеален для логотипов, постеров и рекламы. Balanced — оптимальный баланс качества и скорости, средняя цена.",
    section: "design",
    provider: "replicate",
    familyId: "ideogram",
    variantLabel: "Balanced",
    costUsdPerRequest: 0.06,
    inputCostUsdPerMToken: 0,
    outputCostUsdPerMToken: 0,
    supportsImages: true,
    mediaInputs: [MI_STYLE_REF],
    supportsVoice: false,
    supportsWeb: false,
    isAsync: true,
    maxVirtualBatch: 4,
    contextStrategy: "db_history",
    contextMaxMessages: 0,
    supportedAspectRatios: [
      "1:1",
      "4:3",
      "3:4",
      "16:9",
      "9:16",
      "2:3",
      "3:2",
      "4:5",
      "5:4",
      "2:1",
      "1:2",
      "16:10",
      "10:16",
      "3:1",
      "1:3",
    ],
    settings: IDEOGRAM_SETTINGS,
  },
  "ideogram-turbo": {
    id: "ideogram-turbo",
    name: "✍️ Ideogram v3.0 Turbo",
    description:
      "Лучше всех рисует читаемый текст на картинках. Идеален для логотипов, постеров и рекламы. Turbo — самый быстрый и дешёвый вариант, чуть ниже детализация.",
    section: "design",
    provider: "replicate",
    familyId: "ideogram",
    variantLabel: "Turbo",
    costUsdPerRequest: 0.03,
    inputCostUsdPerMToken: 0,
    outputCostUsdPerMToken: 0,
    supportsImages: true,
    mediaInputs: [MI_STYLE_REF],
    supportsVoice: false,
    supportsWeb: false,
    isAsync: true,
    maxVirtualBatch: 4,
    contextStrategy: "db_history",
    contextMaxMessages: 0,
    supportedAspectRatios: [
      "1:1",
      "4:3",
      "3:4",
      "16:9",
      "9:16",
      "2:3",
      "3:2",
      "4:5",
      "5:4",
      "2:1",
      "1:2",
      "16:10",
      "10:16",
      "3:1",
      "1:3",
    ],
    settings: IDEOGRAM_SETTINGS,
  },
  "imagen-4-fast": {
    id: "imagen-4-fast",
    name: "🔮 Imagen 4 Fast",
    description:
      "Imagen 4 от Google — высокая фотореалистичность. Fast — самый быстрый и дешёвый вариант, без поддержки 2K разрешения. Подходит для быстрых итераций.",
    section: "design",
    provider: "replicate",
    familyId: "imagen",
    versionLabel: "4",
    variantLabel: "Fast",
    costUsdPerRequest: 0.02,
    inputCostUsdPerMToken: 0,
    outputCostUsdPerMToken: 0,
    supportsImages: false,
    supportsVoice: false,
    supportsWeb: false,
    isAsync: true,
    contextStrategy: "db_history",
    contextMaxMessages: 0,
    supportedAspectRatios: ["1:1", "4:3", "3:4", "16:9", "9:16"],
    settings: [
      mkAspectRatio(["1:1", "4:3", "3:4", "16:9", "9:16"]),
      {
        key: "output_format",
        label: "Формат",
        description: "Формат результирующего изображения.",
        type: "select",
        options: [
          { value: "jpg", label: "JPG" },
          { value: "png", label: "PNG" },
        ],
        default: "jpg",
        advanced: true,
      },
      {
        key: "safety_filter_level",
        label: "Фильтр безопасности",
        description:
          "block_only_high — наиболее мягкий, block_medium_and_above — средний, block_low_and_above — строгий.",
        type: "select",
        options: [
          { value: "block_only_high", label: "Мягкий" },
          { value: "block_medium_and_above", label: "Средний" },
          { value: "block_low_and_above", label: "Строгий" },
        ],
        default: "block_only_high",
        advanced: true,
      },
    ],
  },
  "imagen-4": {
    id: "imagen-4",
    name: "🔮 Imagen 4",
    description:
      "Imagen 4 от Google — высокая фотореалистичность. Standard — баланс качества и цены, поддержка 2K разрешения. Оптимальный выбор для большинства задач.",
    section: "design",
    provider: "replicate",
    familyId: "imagen",
    versionLabel: "4",
    variantLabel: "Standard",
    costUsdPerRequest: 0.04,
    inputCostUsdPerMToken: 0,
    outputCostUsdPerMToken: 0,
    supportsImages: false,
    supportsVoice: false,
    supportsWeb: false,
    isAsync: true,
    contextStrategy: "db_history",
    contextMaxMessages: 0,
    supportedAspectRatios: ["1:1", "4:3", "3:4", "16:9", "9:16"],
    settings: [
      mkAspectRatio(["1:1", "4:3", "3:4", "16:9", "9:16"]),
      {
        key: "image_size",
        label: "Разрешение",
        description: "1K — стандартное разрешение, 2K — повышенное. Влияет на время генерации.",
        type: "select",
        options: [
          { value: "1K", label: "1K" },
          { value: "2K", label: "2K" },
        ],
        default: "1K",
      },
      {
        key: "output_format",
        label: "Формат",
        description: "Формат результирующего изображения.",
        type: "select",
        options: [
          { value: "jpg", label: "JPG" },
          { value: "png", label: "PNG" },
        ],
        default: "jpg",
        advanced: true,
      },
      {
        key: "safety_filter_level",
        label: "Фильтр безопасности",
        description:
          "block_only_high — наиболее мягкий, block_medium_and_above — средний, block_low_and_above — строгий.",
        type: "select",
        options: [
          { value: "block_only_high", label: "Мягкий" },
          { value: "block_medium_and_above", label: "Средний" },
          { value: "block_low_and_above", label: "Строгий" },
        ],
        default: "block_only_high",
        advanced: true,
      },
    ],
  },
  "imagen-4-ultra": {
    id: "imagen-4-ultra",
    name: "🔮 Imagen 4 Ultra",
    description:
      "Imagen 4 от Google — высокая фотореалистичность. Ultra — максимальная детализация и качество рендеринга для профессиональных задач, поддержка 2K.",
    section: "design",
    provider: "replicate",
    familyId: "imagen",
    versionLabel: "4",
    variantLabel: "Ultra",
    costUsdPerRequest: 0.06,
    inputCostUsdPerMToken: 0,
    outputCostUsdPerMToken: 0,
    supportsImages: false,
    supportsVoice: false,
    supportsWeb: false,
    isAsync: true,
    contextStrategy: "db_history",
    contextMaxMessages: 0,
    supportedAspectRatios: ["1:1", "4:3", "3:4", "16:9", "9:16"],
    settings: [
      mkAspectRatio(["1:1", "4:3", "3:4", "16:9", "9:16"]),
      {
        key: "image_size",
        label: "Разрешение",
        description: "1K — стандартное разрешение, 2K — повышенное. Влияет на время генерации.",
        type: "select",
        options: [
          { value: "1K", label: "1K" },
          { value: "2K", label: "2K" },
        ],
        default: "1K",
      },
      {
        key: "output_format",
        label: "Формат",
        description: "Формат результирующего изображения.",
        type: "select",
        options: [
          { value: "jpg", label: "JPG" },
          { value: "png", label: "PNG" },
        ],
        default: "jpg",
        advanced: true,
      },
      {
        key: "safety_filter_level",
        label: "Фильтр безопасности",
        description:
          "block_only_high — наиболее мягкий, block_medium_and_above — средний, block_low_and_above — строгий.",
        type: "select",
        options: [
          { value: "block_only_high", label: "Мягкий" },
          { value: "block_medium_and_above", label: "Средний" },
          { value: "block_low_and_above", label: "Строгий" },
        ],
        default: "block_only_high",
        advanced: true,
      },
    ],
  },
  flux: {
    id: "flux",
    name: "⚡ FLUX.2",
    description:
      "Максимально реалистичные фото за секунды. Standard — тонкая настройка генерации (шаги, CFG, ускорение, LoRA). Дешевле Pro, больше параметров.",
    section: "design",
    provider: "fal",
    familyId: "flux",
    versionLabel: "2",
    variantLabel: "Standard",
    costUsdPerRequest: 0,
    costUsdPerMPixel: 0.012, // $0.012/MP, billed as ceil(px/1_000_000)
    // img2img: FAL resizes every input to 1 MP and charges a flat $0.012 per image
    costUsdPerMPixelInput: 0.012,
    costUsdPerMPixelInputFixed: true,
    inputCostUsdPerMToken: 0,
    outputCostUsdPerMToken: 0,
    supportsImages: true,
    mediaInputs: [MI_EDIT_4],
    supportsVoice: false,
    supportsWeb: false,
    isAsync: true,
    // Native batch: fal-ai/flux-2 принимает num_images (1-4) за один call, возвращает
    // массив ImageFile[]. nativeBatchMax > 1 → virtual batch не применяется.
    // chargePerOutput → finalize умножает стоимость на K (FAL биллит per-image-MP).
    nativeBatchMax: 4,
    chargePerOutput: true,
    contextStrategy: "db_history",
    contextMaxMessages: 0,
    // FAL image_size categories: square_hd, landscape_4_3, portrait_4_3, landscape_16_9, portrait_16_9
    supportedAspectRatios: ["1:1", "4:3", "3:4", "16:9", "9:16"],
    settings: [
      NUM_IMAGES_SETTING,
      mkAspectRatio(["1:1", "4:3", "3:4", "16:9", "9:16"]),
      ...FLUX_SETTINGS,
    ],
  },
  "flux-pro": {
    id: "flux-pro",
    name: "⚡ FLUX.2 Pro",
    description:
      "Профессиональная версия FLUX.2 — максимальное качество и точность следования промпту. Меньше ручных настроек, но выше результат из коробки.",
    section: "design",
    provider: "fal",
    familyId: "flux",
    versionLabel: "2",
    variantLabel: "Pro",
    costUsdPerRequest: 0,
    // $0.03 for first MP + $0.015 per extra MP: base=$0.015, perMP=$0.015 → ceil formula
    costUsdPerMPixelBase: 0.015,
    costUsdPerMPixel: 0.015,
    // img2img: +$0.015 per ceil-MP of each input image (sum of ceil per image)
    costUsdPerMPixelInput: 0.015,
    inputCostUsdPerMToken: 0,
    outputCostUsdPerMToken: 0,
    supportsImages: true,
    mediaInputs: [MI_EDIT_4],
    supportsVoice: false,
    supportsWeb: false,
    isAsync: true,
    contextStrategy: "db_history",
    contextMaxMessages: 0,
    supportedAspectRatios: ["1:1", "4:3", "3:4", "16:9", "9:16"],
    settings: [mkAspectRatio(["1:1", "4:3", "3:4", "16:9", "9:16"]), ...FLUX_PRO_SETTINGS],
  },
  "recraft-v3": {
    id: "recraft-v3",
    name: "🖌️ Recraft v3",
    description:
      "Предыдущее поколение Recraft — широкий выбор стилей и под-стилей (реализм, иллюстрация, вектор), настройка художественности. Проверенная стабильность.",
    section: "design",
    provider: "recraft",
    familyId: "recraft",
    versionLabel: "v3",
    variantLabel: "Standard",
    costUsdPerRequest: 0.04,
    inputCostUsdPerMToken: 0,
    outputCostUsdPerMToken: 0,
    supportsImages: true,
    mediaInputs: [MI_EDIT],
    supportsVoice: false,
    supportsWeb: false,
    isAsync: false,
    // Native batch: Recraft API принимает n (1-6) за один call. Биллинг per-image,
    // chargePerOutput → finalize умножит cost на K.
    nativeBatchMax: 6,
    chargePerOutput: true,
    contextStrategy: "db_history",
    contextMaxMessages: 0,
    supportedAspectRatios: ["1:1", "4:3", "3:4", "16:9", "9:16"],
    settings: [
      mkNumImagesSetting(6),
      mkAspectRatio(["1:1", "4:3", "3:4", "16:9", "9:16"]),
      {
        key: "style",
        label: "Стиль",
        description:
          "Художественное направление: реалистичные фото, цифровые иллюстрации или векторная графика.",
        type: "select",
        options: [
          { value: "realistic_image", label: "Реализм" },
          { value: "digital_illustration", label: "Иллюстрация" },
          { value: "vector_illustration", label: "Вектор" },
        ],
        default: "realistic_image",
      },
      {
        key: "substyle",
        label: "Под-стиль",
        description: "Уточняет художественный стиль. Зависит от выбранного стиля.",
        type: "dropdown",
        default: "",
        options: [
          { value: "", label: "— нет —" },
          // realistic_image
          { value: "b_and_w", label: "b_and_w (realistic)" },
          { value: "enterprise", label: "enterprise (realistic)" },
          { value: "evening_light", label: "evening_light (realistic)" },
          { value: "faded_nostalgia", label: "faded_nostalgia (realistic)" },
          { value: "forest_life", label: "forest_life (realistic)" },
          { value: "hard_flash", label: "hard_flash (realistic)" },
          { value: "hdr", label: "hdr (realistic)" },
          { value: "motion_blur", label: "motion_blur (realistic)" },
          { value: "mystic_naturalism", label: "mystic_naturalism (realistic)" },
          { value: "natural_light", label: "natural_light (realistic)" },
          { value: "natural_tones", label: "natural_tones (realistic)" },
          { value: "organic_calm", label: "organic_calm (realistic)" },
          { value: "real_life_glow", label: "real_life_glow (realistic)" },
          { value: "retro_realism", label: "retro_realism (realistic)" },
          { value: "retro_snapshot", label: "retro_snapshot (realistic)" },
          { value: "studio_portrait", label: "studio_portrait (realistic)" },
          { value: "urban_drama", label: "urban_drama (realistic)" },
          { value: "village_realism", label: "village_realism (realistic)" },
          { value: "warm_folk", label: "warm_folk (realistic)" },
          // digital_illustration
          { value: "2d_art_poster", label: "2d_art_poster (digital)" },
          { value: "2d_art_poster_2", label: "2d_art_poster_2 (digital)" },
          { value: "antiquarian", label: "antiquarian (digital)" },
          { value: "bold_fantasy", label: "bold_fantasy (digital)" },
          { value: "child_book", label: "child_book (digital)" },
          { value: "cover", label: "cover (digital)" },
          { value: "crosshatch", label: "crosshatch (digital)" },
          { value: "digital_engraving", label: "digital_engraving (digital)" },
          { value: "engraving_color", label: "engraving_color (digital)" },
          { value: "expressionism", label: "expressionism (digital)" },
          { value: "freehand_details", label: "freehand_details (digital)" },
          { value: "grain", label: "grain (digital)" },
          { value: "grain_20", label: "grain_20 (digital)" },
          { value: "graphic_intensity", label: "graphic_intensity (digital)" },
          { value: "hand_drawn", label: "hand_drawn (digital)" },
          { value: "hand_drawn_outline", label: "hand_drawn_outline (digital)" },
          { value: "handmade_3d", label: "handmade_3d (digital)" },
          { value: "hard_comics", label: "hard_comics (digital)" },
          { value: "infantile_sketch", label: "infantile_sketch (digital)" },
          { value: "long_shadow", label: "long_shadow (digital)" },
          { value: "modern_folk", label: "modern_folk (digital)" },
          { value: "multicolor", label: "multicolor (digital)" },
          { value: "neon_calm", label: "neon_calm (digital)" },
          { value: "noir", label: "noir (digital)" },
          { value: "nostalgic_pastel", label: "nostalgic_pastel (digital)" },
          { value: "outline_details", label: "outline_details (digital)" },
          { value: "pastel_gradient", label: "pastel_gradient (digital)" },
          { value: "pastel_sketch", label: "pastel_sketch (digital)" },
          { value: "pixel_art", label: "pixel_art (digital)" },
          { value: "plastic", label: "plastic (digital)" },
          { value: "pop_art", label: "pop_art (digital)" },
          { value: "pop_renaissance", label: "pop_renaissance (digital)" },
          { value: "seamless", label: "seamless (digital)" },
          { value: "street_art", label: "street_art (digital)" },
          { value: "tablet_sketch", label: "tablet_sketch (digital)" },
          { value: "urban_glow", label: "urban_glow (digital)" },
          { value: "urban_sketching", label: "urban_sketching (digital)" },
          { value: "young_adult_book", label: "young_adult_book (digital)" },
          { value: "young_adult_book_2", label: "young_adult_book_2 (digital)" },
          // vector_illustration
          { value: "bold_stroke", label: "bold_stroke (vector)" },
          { value: "chemistry", label: "chemistry (vector)" },
          { value: "colored_stencil", label: "colored_stencil (vector)" },
          { value: "cosmics", label: "cosmics (vector)" },
          { value: "cutout", label: "cutout (vector)" },
          { value: "depressive", label: "depressive (vector)" },
          { value: "editorial", label: "editorial (vector)" },
          { value: "emotional_flat", label: "emotional_flat (vector)" },
          { value: "engraving", label: "engraving (vector)" },
          { value: "line_art", label: "line_art (vector)" },
          { value: "line_circuit", label: "line_circuit (vector)" },
          { value: "linocut", label: "linocut (vector)" },
          { value: "marker_outline", label: "marker_outline (vector)" },
          { value: "mosaic", label: "mosaic (vector)" },
          { value: "naivector", label: "naivector (vector)" },
          { value: "roundish_flat", label: "roundish_flat (vector)" },
          { value: "seamless", label: "seamless (vector)" },
          { value: "segmented_colors", label: "segmented_colors (vector)" },
          { value: "sharp_contrast", label: "sharp_contrast (vector)" },
          { value: "thin", label: "thin (vector)" },
          { value: "vector_photo", label: "vector_photo (vector)" },
          { value: "vivid_shapes", label: "vivid_shapes (vector)" },
        ],
      },
      {
        key: "no_text",
        label: "Без текста",
        description: "Запретить модели добавлять текст, надписи и леттеринг в изображение.",
        type: "toggle",
        default: false,
      },
      {
        key: "artistic_level",
        label: "Художественность",
        description: "0 — близко к реальности, 5 — максимально стилизованно и художественно.",
        type: "slider",
        min: 0,
        max: 5,
        step: 1,
        default: 2,
        advanced: true,
      },
      {
        key: "strength",
        label: "Сила изменения",
        description:
          "Применяется при редактировании изображения. 0 — почти не изменять оригинал, 1 — следовать только промпту.",
        type: "slider",
        min: 0,
        max: 1,
        step: 0.05,
        default: 0.5,
        advanced: true,
      },
    ],
  },
  "recraft-v4": {
    id: "recraft-v4",
    name: "🖌️ Recraft V4",
    description:
      "Recraft V4 Standard — новое поколение для дизайна и маркетинга. Чистая композиция и точный рендеринг текста. Дешевле Pro, меньше детализация.",
    section: "design",
    provider: "recraft",
    familyId: "recraft",
    versionLabel: "v4",
    variantLabel: "Standard",
    costUsdPerRequest: 0.04,
    inputCostUsdPerMToken: 0,
    outputCostUsdPerMToken: 0,
    supportsImages: true,
    mediaInputs: [MI_EDIT],
    supportsVoice: false,
    supportsWeb: false,
    isAsync: false,
    nativeBatchMax: 6,
    chargePerOutput: true,
    contextStrategy: "db_history",
    contextMaxMessages: 0,
    supportedAspectRatios: ["1:1", "4:3", "3:4", "16:9", "9:16"],
    settings: [
      mkNumImagesSetting(6),
      mkAspectRatio(["1:1", "4:3", "3:4", "16:9", "9:16"]),
      {
        key: "strength",
        label: "Сила изменения",
        description:
          "Применяется при редактировании изображения. 0 — почти не изменять оригинал, 1 — следовать только промпту.",
        type: "slider",
        min: 0,
        max: 1,
        step: 0.05,
        default: 0.5,
        advanced: true,
      },
      {
        key: "seed",
        label: "Seed",
        description:
          "Число для воспроизведения результата. Пусто — случайный результат каждый раз.",
        type: "number",
        min: 0,
        max: 2147483647,
        default: null,
        advanced: true,
      },
    ],
  },
  "recraft-v4-pro": {
    id: "recraft-v4-pro",
    name: "💠 Recraft V4 Pro",
    description:
      "Recraft V4 Pro — максимальное разрешение и детализация растровых изображений. Идеален для ответственных дизайн-проектов, готовых в производство без правок.",
    section: "design",
    provider: "recraft",
    familyId: "recraft",
    versionLabel: "v4",
    variantLabel: "Pro",
    costUsdPerRequest: 0.25,
    inputCostUsdPerMToken: 0,
    outputCostUsdPerMToken: 0,
    supportsImages: true,
    mediaInputs: [MI_EDIT],
    supportsVoice: false,
    supportsWeb: false,
    isAsync: false,
    nativeBatchMax: 6,
    chargePerOutput: true,
    contextStrategy: "db_history",
    contextMaxMessages: 0,
    supportedAspectRatios: ["1:1", "4:3", "3:4", "16:9", "9:16"],
    settings: [
      mkNumImagesSetting(6),
      mkAspectRatio(["1:1", "4:3", "3:4", "16:9", "9:16"]),
      {
        key: "strength",
        label: "Сила изменения",
        description:
          "Применяется при редактировании изображения. 0 — почти не изменять оригинал, 1 — следовать только промпту.",
        type: "slider",
        min: 0,
        max: 1,
        step: 0.05,
        default: 0.5,
        advanced: true,
      },
      {
        key: "seed",
        label: "Seed",
        description:
          "Число для воспроизведения результата. Пусто — случайный результат каждый раз.",
        type: "number",
        min: 0,
        max: 2147483647,
        default: null,
        advanced: true,
      },
    ],
  },
  "recraft-v4-vector": {
    id: "recraft-v4-vector",
    name: "📐 Recraft V4 Vector (SVG)",
    description:
      "Recraft V4 Vector — генерирует SVG-векторы для логотипов, иконок и иллюстраций. Масштабируются без потери качества. Стандартная версия — дешевле Pro Vector.",
    section: "design",
    provider: "recraft",
    familyId: "recraft",
    versionLabel: "v4",
    variantLabel: "Vector",
    costUsdPerRequest: 0.08,
    inputCostUsdPerMToken: 0,
    outputCostUsdPerMToken: 0,
    supportsImages: true,
    mediaInputs: [MI_EDIT],
    supportsVoice: false,
    supportsWeb: false,
    isAsync: false,
    nativeBatchMax: 6,
    chargePerOutput: true,
    contextStrategy: "db_history",
    contextMaxMessages: 0,
    supportedAspectRatios: ["1:1", "4:3", "3:4", "16:9", "9:16"],
    settings: [
      mkNumImagesSetting(6),
      {
        key: "strength",
        label: "Сила изменения",
        description:
          "Применяется при редактировании изображения. 0 — почти не изменять оригинал, 1 — следовать только промпту.",
        type: "slider",
        min: 0,
        max: 1,
        step: 0.05,
        default: 0.5,
        advanced: true,
      },
      {
        key: "seed",
        label: "Seed",
        description:
          "Число для воспроизведения результата. Пусто — случайный результат каждый раз.",
        type: "number",
        min: 0,
        max: 2147483647,
        default: null,
        advanced: true,
      },
    ],
  },
  "recraft-v4-pro-vector": {
    id: "recraft-v4-pro-vector",
    name: "📐 Recraft V4 Pro Vector (SVG)",
    description:
      "Recraft V4 Pro Vector — максимальное качество SVG-генерации. Подходит для сложных иллюстраций и брендинга, где требуется безупречная детализация и масштабируемость.",
    section: "design",
    provider: "recraft",
    familyId: "recraft",
    versionLabel: "v4",
    variantLabel: "Pro Vector",
    costUsdPerRequest: 0.3,
    inputCostUsdPerMToken: 0,
    outputCostUsdPerMToken: 0,
    supportsImages: true,
    mediaInputs: [MI_EDIT],
    supportsVoice: false,
    supportsWeb: false,
    isAsync: false,
    nativeBatchMax: 6,
    chargePerOutput: true,
    contextStrategy: "db_history",
    contextMaxMessages: 0,
    supportedAspectRatios: ["1:1", "4:3", "3:4", "16:9", "9:16"],
    settings: [
      mkNumImagesSetting(6),
      {
        key: "strength",
        label: "Сила изменения",
        description:
          "Применяется при редактировании изображения. 0 — почти не изменять оригинал, 1 — следовать только промпту.",
        type: "slider",
        min: 0,
        max: 1,
        step: 0.05,
        default: 0.5,
        advanced: true,
      },
      {
        key: "seed",
        label: "Seed",
        description:
          "Число для воспроизведения результата. Пусто — случайный результат каждый раз.",
        type: "number",
        min: 0,
        max: 2147483647,
        default: null,
        advanced: true,
      },
    ],
  },
  "stable-diffusion": {
    id: "stable-diffusion",
    name: "🌊 Stable Diffusion 3.5 Medium",
    description:
      "Генерирует детальные изображения в любом стиле: от фотореализма до аниме и фэнтези. Отличается гибкостью. Работает только с промптами на анлгийском языке!",
    section: "design",
    provider: "replicate",
    costUsdPerRequest: 0.065,
    inputCostUsdPerMToken: 0,
    outputCostUsdPerMToken: 0,
    supportsImages: true,
    mediaInputs: [MI_EDIT],
    supportsVoice: false,
    supportsWeb: false,
    isAsync: true,
    contextStrategy: "db_history",
    contextMaxMessages: 0,
    // Replicate/SDXL accepts arbitrary dimensions — offer extended set
    supportedAspectRatios: ["1:1", "16:9", "21:9", "2:3", "3:2", "4:5", "5:4", "9:16", "9:21"],
    settings: [
      {
        key: "auto_translate_prompt",
        label: "Автоперевод промпта",
        description:
          "Эта модель работает только (либо значительно лучше) с промптами на английском языке, мы можем перевести его для вас за отдельную плату.",
        type: "toggle",
        default: false,
      },
      mkAspectRatio(["1:1", "16:9", "21:9", "2:3", "3:2", "4:5", "5:4", "9:16", "9:21"]),
      {
        key: "negative_prompt",
        label: "Негативный промпт",
        description:
          "Что НЕ должно быть на картинке: перечислите нежелательные объекты, стили или черты.",
        type: "text",
        default: "",
        advanced: true,
      },
      {
        key: "cfg",
        label: "Следование промпту (CFG)",
        description:
          "Насколько строго ИИ следует тексту. Высокие значения — буквально, низкие — с творческой интерпретацией.",
        type: "slider",
        min: 1,
        max: 10,
        step: 0.5,
        default: 5,
        advanced: true,
      },
      {
        key: "prompt_strength",
        label: "Сила промпта (img2img)",
        description:
          "Степень изменения при img2img. 0.1 = минимальные изменения, 1.0 = полная замена.",
        type: "slider",
        min: 0.1,
        max: 1,
        step: 0.05,
        default: 0.85,
        advanced: true,
      },
      {
        key: "output_format",
        label: "Формат",
        description: "Формат результирующего изображения.",
        type: "select",
        options: [
          { value: "png", label: "PNG" },
          { value: "webp", label: "WebP" },
          { value: "jpg", label: "JPEG" },
        ],
        default: "png",
        advanced: true,
      },
      {
        key: "seed",
        label: "Seed",
        description: "Фиксированный seed для воспроизводимости результата.",
        type: "number",
        min: 0,
        default: null,
        advanced: true,
      },
    ],
  },
  // DALL-E 3 DEPRECATED
  // "dall-e-3": {
  //   id: "dall-e-3",
  //   name: "🎯 DALL-E 3 Turbo",
  //   description:
  //     "Простой и понятный генератор от OpenAI. Хорошо понимает запросы на любом языке, отлично для быстрых идей.",
  //   section: "design",
  //   provider: "openai",
  //   // Base: standard 1024×1024. Exact cost = quality × size (see costMatrix).
  //   costUsdPerRequest: 0.04,
  //   costMatrix: {
  //     dims: ["quality", "aspect_ratio"],
  //     table: {
  //       "standard__1:1": 0.04,
  //       "standard__16:9": 0.08,
  //       "standard__9:16": 0.08,
  //       "hd__1:1": 0.08,
  //       "hd__16:9": 0.12,
  //       "hd__9:16": 0.12,
  //     },
  //   },
  //   inputCostUsdPerMToken: 0,
  //   outputCostUsdPerMToken: 0,
  //   supportsImages: false,
  //   supportsVoice: false,
  //   supportsWeb: false,
  //   isAsync: false,
  //   maxVirtualBatch: 4,
  //   contextStrategy: "db_history",
  //   contextMaxMessages: 0,
  //   // DALL-E 3 only supports exactly 3 sizes
  //   supportedAspectRatios: ["1:1", "16:9", "9:16"],
  //   settings: [
  //     NUM_IMAGES_SETTING,
  //     mkAspectRatio(["1:1", "16:9", "9:16"]),
  //     {
  //       key: "quality",
  //       label: "Качество",
  //       description: "Standard — быстрее и дешевле, HD — более детальная и сложная картинка.",
  //       type: "select",
  //       options: [
  //         { value: "standard", label: "Standard" },
  //         { value: "hd", label: "HD" },
  //       ],
  //       default: "standard",
  //     },
  //     {
  //       key: "style",
  //       label: "Стиль",
  //       description:
  //         "Vivid — насыщенные цвета, яркий и выразительный результат. Natural — более спокойный и реалистичный.",
  //       type: "select",
  //       options: [
  //         { value: "vivid", label: "Vivid" },
  //         { value: "natural", label: "Natural" },
  //       ],
  //       default: "vivid",
  //     },
  //   ],
  // },
};

/**
 * Fallback-альтернативы для дизайн-моделей. `id` совпадает с primary
 * из DESIGN_MODELS; `provider` (и всё остальное) — собственное.
 * При недоступности primary processor возьмёт первую запись с тем же id,
 * совместимую с media-режимом задачи (см. isFallbackCompatible).
 *
 * Пустой массив = fallback выключен. Цена для биллинга всегда берётся
 * из primary, независимо от того, какой fallback сработал.
 *
 * Записи здесь НЕ попадают в AI_MODELS (там id'ы уникальны = primary).
 * Используются только image processor'ом для подбора альтернативного
 * адаптера; fields name/description/settings игнорируются UX-уровнем.
 * Минимально нужны: id, provider, mediaInputs (для isFallbackCompatible).
 */
export const FALLBACK_DESIGN_MODELS: AIModel[] = [
  // ── Nano Banana семейство через evolink (https://api.evolink.ai) ────────────
  // KIE primary'и роутятся на evolink-аналоги:
  //   nano-banana-1   → nano-banana-beta
  //   nano-banana-2   → gemini-3.1-flash-image-preview
  //   nano-banana-pro → gemini-3-pro-image-preview
  // Биллинг всегда по primary (KIE-цена), при fallback'е providerUsdCost не учитывается.
  // ── Nano Banana PRO (evolink: gemini-3-pro-image-preview) ──────────────────
  // Pricing (per evolink docs):
  //   - Output image: $0.125 (1K/2K), $0.224 (4K)
  //   - Reference image: $0.0010/image (charged per uploaded image)
  //   - Web search: $0.013/request when enabled
  //   - Input text: $0.0019/1K tokens, output+thinking: $0.011/1K tokens
  // Text tokens не биллятся в image processor (он передаёт 0,0 в calculateCost) —
  // зашиты в AIModel для документации/будущей интеграции через providerUsdCost.
  {
    id: "nano-banana-pro",
    name: "Nano Banana PRO (evolink fallback)",
    description: "Fallback на evolink при недоступности KIE.",
    section: "design",
    provider: "evolink",
    costUsdPerRequest: 0.125, // base = output 1K/2K
    costVariants: {
      settingKey: "resolution",
      map: { "1K": 0.125, "2K": 0.125, "4K": 0.224 },
    },
    costUsdPerMPixelInput: 0.001, // $0.0010 per reference image (Fixed=true)
    costUsdPerMPixelInputFixed: true,
    costAddons: [{ settingKey: "enable_web_search", map: { true: 0.013 } }],
    inputCostUsdPerMToken: 1.9, // $0.0019/1K = $1.9/1M (документация)
    outputCostUsdPerMToken: 11, // $0.011/1K = $11/1M (документация)
    supportsImages: true,
    mediaInputs: [{ slotKey: "edit", mode: "edit", labelKey: "multiple_edit", maxImages: 14 }],
    supportsVoice: false,
    supportsWeb: false,
    isAsync: true,
    contextStrategy: "db_history",
    contextMaxMessages: 0,
    supportedAspectRatios: [
      "auto",
      "21:9",
      "16:9",
      "3:2",
      "4:3",
      "5:4",
      "1:1",
      "4:5",
      "3:4",
      "2:3",
      "9:16",
    ],
    // Settings — отображаются только если модель промоутится в primary (т.е.
    // запись попадает в DESIGN_MODELS / AI_MODELS). В fallback состоянии
    // settings игнорируются UI'ем (FALLBACK_DESIGN_MODELS не сериализуется
    // через /models route). Преbuild'нуты для plug-and-play promotion.
    settings: [
      mkAspectRatio([
        "auto",
        "21:9",
        "16:9",
        "3:2",
        "4:3",
        "5:4",
        "1:1",
        "4:5",
        "3:4",
        "2:3",
        "9:16",
      ]),
      {
        key: "resolution",
        label: "Разрешение",
        description: "1K/2K — стандарт, 4K — максимальные детали (дороже).",
        type: "select",
        options: [
          { value: "1K", label: "1K" },
          { value: "2K", label: "2K" },
          { value: "4K", label: "4K" },
        ],
        default: "1K",
      },
      {
        key: "enable_web_search",
        label: "Web search",
        description: "Подключить веб-поиск к генерации (учитывается актуальный контекст).",
        type: "toggle",
        default: false,
        advanced: true,
      },
    ],
  },
  // ── Nano Banana 2 (evolink: gemini-3.1-flash-image-preview) ─────────────────
  // Pricing:
  //   - Output image varies by quality:
  //     0.5K=$0.042, 1K=$0.063, 2K=$0.094, 4K=$0.141
  //   - Reference image: $0.0005/image
  //   - Web search: $0.013/request, Image search: $0.013/request
  //   - Input text: $0.0005/1K, output+thinking: $0.0028/1K
  {
    id: "nano-banana-2",
    name: "Nano Banana 2 (evolink fallback)",
    description: "Fallback на evolink при недоступности KIE.",
    section: "design",
    provider: "evolink",
    costUsdPerRequest: 0.063, // base = output 1K
    costVariants: {
      settingKey: "resolution",
      map: { "0.5K": 0.042, "1K": 0.063, "2K": 0.094, "4K": 0.141 },
    },
    costUsdPerMPixelInput: 0.0005,
    costUsdPerMPixelInputFixed: true,
    costAddons: [
      { settingKey: "enable_web_search", map: { true: 0.013 } },
      { settingKey: "image_search", map: { true: 0.013 } },
    ],
    inputCostUsdPerMToken: 0.5, // $0.0005/1K = $0.5/1M
    outputCostUsdPerMToken: 2.8, // $0.0028/1K = $2.8/1M
    supportsImages: true,
    mediaInputs: [{ slotKey: "edit", mode: "edit", labelKey: "multiple_edit", maxImages: 14 }],
    supportsVoice: false,
    supportsWeb: false,
    isAsync: true,
    contextStrategy: "db_history",
    contextMaxMessages: 0,
    supportedAspectRatios: [
      "auto",
      "21:9",
      "16:9",
      "4:3",
      "3:2",
      "5:4",
      "1:1",
      "4:5",
      "2:3",
      "3:4",
      "9:16",
      "8:1",
      "4:1",
      "1:4",
      "1:8",
    ],
    settings: [
      mkAspectRatio([
        "auto",
        "21:9",
        "16:9",
        "4:3",
        "3:2",
        "5:4",
        "1:1",
        "4:5",
        "2:3",
        "3:4",
        "9:16",
        "8:1",
        "4:1",
        "1:4",
        "1:8",
      ]),
      {
        key: "resolution",
        label: "Разрешение",
        description: "0.5K — самый дешёвый, 4K — максимальные детали.",
        type: "select",
        options: [
          { value: "0.5K", label: "0.5K" },
          { value: "1K", label: "1K" },
          { value: "2K", label: "2K" },
          { value: "4K", label: "4K" },
        ],
        default: "1K",
      },
      {
        key: "enable_web_search",
        label: "Web search",
        description: "Подключить веб-поиск к генерации.",
        type: "toggle",
        default: false,
        advanced: true,
      },
      {
        key: "image_search",
        label: "Image search",
        description: "Подключить поиск референсных изображений в вебе.",
        type: "toggle",
        default: false,
        advanced: true,
      },
      {
        key: "thinking_level",
        label: "Глубина рассуждений",
        description: "min — быстрее, high — качественнее.",
        type: "select",
        options: [
          { value: "auto", label: "auto" },
          { value: "min", label: "min" },
          { value: "high", label: "high" },
        ],
        default: "auto",
        advanced: true,
      },
    ],
  },
  // ── Nano Banana v1 (evolink: nano-banana-beta) ──────────────────────────────
  // Pricing: $0.024/image flat (no quality / search / per-input charges).
  {
    id: "nano-banana-1",
    name: "Nano Banana (evolink fallback)",
    description: "Fallback на evolink при недоступности KIE.",
    section: "design",
    provider: "evolink",
    costUsdPerRequest: 0.024,
    inputCostUsdPerMToken: 0,
    outputCostUsdPerMToken: 0,
    supportsImages: true,
    // evolink nano-banana-beta: до 5 reference images. Primary KIE — 10.
    // Если user загрузил 6-10 картинок, isFallbackCompatible вернёт false и
    // fallback не сработает — это корректное consrative-поведение.
    mediaInputs: [{ slotKey: "edit", mode: "edit", labelKey: "multiple_edit", maxImages: 5 }],
    supportsVoice: false,
    supportsWeb: false,
    isAsync: true,
    contextStrategy: "db_history",
    contextMaxMessages: 0,
    supportedAspectRatios: ["auto", "16:9", "3:2", "4:3", "1:1", "3:4", "2:3", "9:16"],
    settings: [mkAspectRatio(["auto", "16:9", "3:2", "4:3", "1:1", "3:4", "2:3", "9:16"])],
  },
  // ── GPT Image 2 via evolink (fallback к KIE primary) ─────────────────────────
  // Pricing — копия OpenAI costMatrix × 0.9 (10% дешевле). Структура dims/keys
  // совпадает с OpenAI fallback ниже, чтобы при промоушене любого из этих
  // fallback'ов в primary settings + cost оставались согласованными.
  //
  // Адаптер EvolinkImageAdapter принимает оба формата settings:
  //   - KIE-style: aspect_ratio (ratio) + resolution (1K/2K/4K)
  //   - OpenAI-style: size (pixel format) + quality (low/medium/high)
  // — это позволяет fallback'у работать прозрачно при текущем KIE primary.
  {
    id: "gpt-image-2",
    name: "GPT Image 2 (evolink fallback)",
    description: "Fallback на evolink при недоступности KIE.",
    section: "design",
    provider: "evolink",
    costUsdPerRequest: 0.0477, // base = medium 1024×1024 (openai $0.053 × 0.9)
    costMatrix: {
      dims: ["quality", "size"],
      table: {
        // openai × 0.9
        low__1024x1024: 0.0054,
        low__1536x1024: 0.0045,
        low__1024x1536: 0.0045,
        low__2048x2048: 0.0108,
        low__2048x1152: 0.0045,
        low__1152x2048: 0.0045,
        low__3840x2160: 0.0099,
        low__2160x3840: 0.0099,
        low__auto: 0.0054,
        medium__1024x1024: 0.0477,
        medium__1536x1024: 0.0369,
        medium__1024x1536: 0.0369,
        medium__2048x2048: 0.0963,
        medium__2048x1152: 0.0378,
        medium__1152x2048: 0.0378,
        medium__3840x2160: 0.09,
        medium__2160x3840: 0.09,
        medium__auto: 0.0477,
        high__1024x1024: 0.1899,
        high__1536x1024: 0.1485,
        high__1024x1536: 0.1485,
        high__2048x2048: 0.3852,
        high__2048x1152: 0.153,
        high__1152x2048: 0.153,
        high__3840x2160: 0.36,
        high__2160x3840: 0.36,
        high__auto: 0.1899,
        auto__1024x1024: 0.0477,
        auto__1536x1024: 0.0369,
        auto__1024x1536: 0.0369,
        auto__2048x2048: 0.1908,
        auto__2048x1152: 0.0558,
        auto__1152x2048: 0.0558,
        auto__3840x2160: 0.1944,
        auto__2160x3840: 0.1944,
        auto__auto: 0.0477,
      },
    },
    inputCostUsdPerMToken: 0,
    outputCostUsdPerMToken: 0,
    supportsImages: true,
    mediaInputs: [MI_EDIT_4],
    supportsVoice: false,
    supportsWeb: false,
    isAsync: true,
    contextStrategy: "db_history",
    contextMaxMessages: 0,
    supportedAspectRatios: null,
    settings: [
      {
        key: "size",
        label: "Размер",
        description:
          "1024×1024 — квадрат, 1536×1024 — альбом, 1024×1536 — портрет. 2K/3840 — экспериментальные. Auto — модель сама подберёт. Влияет на цену.",
        type: "select",
        options: [
          { value: "1024x1024", label: "1024 × 1024" },
          { value: "1536x1024", label: "1536 × 1024 (16:9)" },
          { value: "1024x1536", label: "1024 × 1536 (9:16)" },
          { value: "2048x2048", label: "2048 × 2048 (2K)" },
          { value: "2048x1152", label: "2048 × 1152 (2K 16:9)" },
          { value: "1152x2048", label: "1152 × 2048 (2K 9:16)" },
          { value: "3840x2160", label: "3840 × 2160 (4K 16:9)" },
          { value: "2160x3840", label: "2160 × 3840 (4K 9:16)" },
          { value: "auto", label: "Auto" },
        ],
        default: "1024x1024",
      },
      {
        key: "quality",
        label: "Качество",
        description: "Low — быстро, Medium — баланс, High — максимум. Влияет на цену.",
        type: "select",
        options: [
          { value: "low", label: "Low" },
          { value: "medium", label: "Medium" },
          { value: "high", label: "High" },
          { value: "auto", label: "Auto" },
        ],
        default: "medium",
      },
    ],
  },
  // ── Image upscale fallback (evolink: gemini-3-pro-image-preview) ────────────
  // Готовый сценарий «Апскейл фото» = nano-banana-pro под капотом. KIE primary
  // `image-upscale` фолбэчится на evolink ровно как nano-banana-pro.
  //
  // Списание с ЮЗЕРА — всегда по primary (image processor при usedFallback
  // считает цену primary-моделью). НО `costUsdPerRequest` отсюда идёт в
  // audit-метаданные `actualCostUsd` (фактическая провайдерская стоимость) —
  // поэтому держим реальную цену evolink на 4K, а не primary-шную $0.12.
  {
    id: "image-upscale",
    name: "📷 Апскейл фото (evolink fallback)",
    description: "Fallback на evolink при недоступности KIE.",
    section: "design",
    provider: "evolink",
    costUsdPerRequest: 0.224, // evolink gemini-3-pro-image @ 4K — для actualCostUsd-аудита
    inputCostUsdPerMToken: 0,
    outputCostUsdPerMToken: 0,
    supportsImages: true,
    supportsVoice: false,
    supportsWeb: false,
    isAsync: true,
    hiddenFromCarousel: true,
    deliverAsDocument: true,
    contextStrategy: "db_history",
    contextMaxMessages: 0,
    supportedAspectRatios: ["auto"],
    mediaInputs: [{ slotKey: "edit", mode: "edit", labelKey: "multiple_edit", maxImages: 1 }],
  },
];
